# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df1c72db20373907e234a86f9262b27b39b908f730733b331703d3b8a8f7639d4d974458fc5d6b04f6043ab5d18eb08c96d3f6df9270cc95c7f0df39e44a148e

test:
  secret_key_base: dc2a03343d0e2d84cce7400a18d0ee7cd61007b7a9bba9e13c63c9938409ba89591d14b9bbabbe9462ced1bf56e951150880a2643e540c2ad8d5143d3671cdb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
